databases:
  - name: postgres
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    plan: free
    name: eighthon
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: gunicorn app:app & python3 -m eighthon.py
    region: frankfurt
    repo: https://github.com/rick1128/eighthon     
    branch: master
    envVars:
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: TERMUX
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.5 
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString   
    autoDeploy: false
